### ISSUE TITLE
Error: Cannot find module '../build/Release/volume.node'

### ISSUE THREAD

**Issue by shubh802** [LinusU/node-appdmg#154]
while running below command am getting this error....

appdmg ./CTFAppCreation.json ./DCM.dmg
module.js:538
    throw err;
    ^

Error: Cannot find module '../build/Release/volume.node'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/appdmg/node_modules/macos-alias/lib/create.js:7:13)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

**Comment by shubh802** [comment]
I have tried re installing appdmg

**Comment by anurag-sinha** [comment]
TO workaround the issue, we remove the reference to Volume.node and tried hard-coding it;s usage. Post that it was able to move ahead but then failed at ./build/Release/xattr  module not found.  Any suggestions?

**Comment by shubh802** [comment]
We are able to solve this actually appdmg uses node-gyp module as the dependency, node-gyp module could only work with python 2.7 it does not support python3.4 so by uninstalling and reinstalling appdmg from python 2.7 resolved it
by below command
npm install -g appdmg --python=python2.7

**Comment by noahott** [comment]
I'm still seeing this error and only have Python 2.7 installed. I'm running MacOS High Sierra 10.13.3

**Comment by rendertom** [comment]
Same issue here on OSx 10.12.6
Running npm install -g appdmg --python=python2.7 did not help.

**Comment by shubh802** [comment]
Can you give some more details I remember I have to rebuild node-gyp module

**Comment by obiwankennedy** [comment]
same issue here, I have MacOS High Sierra 10.13.3 and it does not work

**Comment by dvdsosa** [comment]
same issue... please post how did you resolve this.

**Comment by scottcarter** [comment]
I also hit this problem.  My npm packages were being installed to /usr/local/lib/node_modules

I tried installing appdmg as root, but was getting an EACCES error.   This is referenced at [How to Install Global Packages](https://docs.npmjs.com/getting-started/installing-npm-packages-globally)

The solution for me was to install npm packages to my local directory as mentioned at [How to Prevent Permissions Errors](https://docs.npmjs.com/getting-started/fixing-npm-permissions)  (I chose Option Two: Change npm's Default Directory).

After switching to a local directory install, "npm install -g appdmg" worked perfectly.

**Comment by LinusU** [comment]
As mentioned before, node-gyp requires Python 2.x. Happy to reopen if the issue persists...

**Comment by aimerib** [comment]
For anyone coming here from the distant future using an electron-forge project, the version of appdmg used by that project is outdated, and had a dependency of fs-xattr lower than 0.3. node-gyp fails to compile fs-xattr on node v12 as per [this issue](https://github.com/LinusU/fs-xattr/issues/27)

For me, the fix was to update fs-xattr to a newer version. Another possible fix (untested as of yet) would be to update appdmg directly since as of the current version of appdmg it depends on the correct version of fs-xattr for newer versions of node.
